### ISSUE TITLE
Cannot read property 'slugify' of undefined

### ISSUE THREAD

**Issue by kylos101** [srsgores/generator-wordpress-plugin#5]
Hello, this error is received when trying to use the generator. I'd be happy to help debug - got any tips for digging into this?

C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'slugify' of undefined
    at wordpressPluginGenerator.<anonymous> (C:\Users\Kyle\AppData\Roaming\npm\node_modules\generator-wordpress-plugin\app\index.js:83:31)
    at wordpressPluginGenerator.<anonymous> (C:\Users\Kyle\AppData\Roaming\npm\node_modules\generator-wordpress-plugin\node_modules\yeoman-generator\lib\base.js:233:7)
    at PromptUI.onCompletion (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\ui\prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:1730:14)
    at AnonymousObserver.tryCatcher (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.completed (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:1730:14)
    at InnerObserver.onCompleted (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:3425:65)
    at InnerObserver.tryCatcher (C:\Users\Kyle\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)

**Comment by srsgores** [comment]
Probably due to #3

**Comment by srsgores** [comment]
Can you provide the options you used to generate the error?

**Comment by kylos101** [comment]
Certainly, I'm traveling now, but can share later tonight or tomorrow
morning.

**Comment by kylos101** [comment]
C:\Users\firstName\Documents\GitHub\Cloud Storage-Browser>yo wordpress-plugin
(!) this.readFileAsString() is deprecated. Use require("html-wiring").readFileAsString() instead.
undefined
? What is the name of the new wordpress plugin? Cloud Storage Browser
? Give me a description on what your plugin is supposed to do: Browse content
? Who is the creator of this style? firstName LastName
? What is your primary e-mail address: firstNickName101@gmail.com
? What is the site where the author can be reached? http://firstNickName.net
? What is your gitHub account? firstNickName101
? What is your Twitter account? @firstNickName101
? (optional) What is your company name? Company Name
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
C:\Users\firstName\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.js:579
    throw e;

**Comment by Tropicalista** [comment]
Same error here. Please could you share if you found a solution? Thanks

**Comment by vimes1984** [comment]
I think my patch hasn't been pushed to npm. 
If you use the version here on github it works just fine.. 
https://github.com/srsgores/generator-wordpress-plugin
